FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libxml2-dev \
    libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY downloader.py .
COPY templates ./templates
COPY static ./static

ENV VIDEO_ROOT_DIR=/videos

EXPOSE 16969

CMD ["python", "app.py"]
